"""Markdown formatter for editorials."""

from domain.models import Editorial, ProblemData


class MarkdownFormatter:
    """Formats editorial as Markdown."""

    @staticmethod
    def format(editorial: Editorial, problem: ProblemData) -> str:
        """
        Format editorial as Markdown.

        Args:
            editorial: Editorial to format
            problem: Problem data

        Returns:
            Formatted Markdown string
        """
        lines = []

        # Metadata header
        lines.append("---")
        lines.append(f"Problem: {problem.identifier.problem_id}")
        lines.append(f"Contest: {problem.identifier.contest_id}")
        lines.append(f"Title: {problem.title}")
        lines.append(f"Link: {problem.url}")
        if editorial.source_url:
            lines.append(f"Editorial: {editorial.source_url}")
        lines.append("---")
        lines.append("")

        # Original editorial text (preserves all formatting)
        lines.append(editorial.solution_text)
        lines.append("")

        # Footer
        lines.append("---")
        lines.append("*Generated by codeforces-editorial-finder*")
        lines.append("")

        return "\n".join(lines)


def format_editorial_markdown(editorial: Editorial, problem: ProblemData) -> str:
    """
    Convenience function to format editorial.

    Args:
        editorial: Editorial
        problem: Problem data

    Returns:
        Markdown string
    """
    return MarkdownFormatter.format(editorial, problem)
